### ISSUE TITLE
Pipeline not working on test environment

### ISSUE THREAD

**Issue by itsJoKr** [peh/react-grails-asset-pipeline#11]
Hi. Your plugin worked on fine on development. But when I exported test war and deployed it, it seems that jsx files are not complied.

For example, I had this file editor.js with just these two lines:

```
//= require jsx/title.jsx
//= require jsx/root.jsx
```

That worked on development, and I would get separated compiled js files. Now, on test war, I expected they should be packed in editor.js and minified, but this is how my editor.js looks:

```
//# sourceMappingURL=editor.js.map

```

I would expect bunch of minifed code below this first line (like application.js).

**Comment by peh** [comment]
hey, i would recommend moving to https://github.com/peh/grails-babel-asset-pipeline
it does the JSX transformation to and you are not stuck with react 0.12. 
i should mark this plugin as deprecated.
migration should be easy (just replace in buildconfig, download the newest react and require it in your jsx assets, thats basicly it

**Comment by itsJoKr** [comment]
It works now. Thank you very much.

I just replaced plugin in BuildConfig and it works. I was already using newest React.

**Comment by peh** [comment]
perfect.
