### ISSUE TITLE
How do I enable the harmony option?

### ISSUE THREAD

**Issue by tobia** [peh/react-grails-asset-pipeline#3]
Also, why does `:react-asset-pipeline:1.1.1` depend on another plugin `net.errbuddy.plugins:react-asset-pipeline:1.0.7` with a different version that is taken from a custom MVN repo?

That's a bit convoluted. Wouldn't it be easier to just package all the classes you need in this plugin?

**Comment by peh** [comment]
no. this is how asset-pipeline works. you have to provide it with a binary plugin (which is the referenced plugin with the custom repo).
with grails 3 everything is a binary plugin and you will not need the "wrapper grails plugin" anymore.

**Comment by peh** [comment]
merged and released.
