### ISSUE TITLE
Hard-coded environment in ReactTagLib

### ISSUE THREAD

**Issue by tobia** [peh/react-grails-asset-pipeline#4]
This line in ReactTagLib:

```
def debugMode = (conf.allowDebugParam && debugParameter) || 
                (Environment.current == Environment.DEVELOPMENT && 
                    !grailsApplication.warDeployed && conf.bundle != true)
```

does not take into consideration custom environments.

Medium- to large-size Grails apps have many environments, used for various development purposes, testing, QA, demos, or different kinds of production deployments.

The standard plugins are aware of this and only use the three default environments to set the default values of their configuration variables, never directly their behaviour.

In this case I suggest removing the environment check and leaving the others, which should suffice:

```
def debugMode = (conf.allowDebugParam && debugParameter) || 
                (!grailsApplication.warDeployed && conf.bundle != true)
```

**Comment by peh** [comment]
merged and released
